##' Build an odin model generator from its intermediate
##' representation, as generated by \code{\link{odin_parse}}.  This
##' function is for advanced use.
##'
##' In applications that want to inspect the intermediate
##' representation rather before compiling, rather than directly using
##' \code{\link{odin}}, use either \code{\link{odin_parse}} or
##' \code{\link{odin_validate}} and then pass the result to
##' \code{odin_build}.
##'
##' @title Build an odin model generator from its IR
##'
##' @param x An odin ir (json) object or output from
##'   \code{\link{odin_validate}}.
##'
##' @param options Options to pass to the build stage (see
##'   \code{\link{odin_options}}
##'
##' @export
odin_build <- function(x, options = NULL) {
  options <- odin_options(options = options)

  if (is.list(x) && inherits(x$result, "json")) {
    x <- x$result
  } else if (!inherits(x, "json")) {
    stop("Expected an odin intermediate representation")
  }

  elapsed <- system.time(
    output <- utils::capture.output(
      suppressMessages(
        model <- tryCatch(
          odin_generate(x, options),
          error = identity))),
    gcFirst = FALSE)

  is_error <- inherits(model, "error")

  if (is_error) {
    error <- model$message
    model <- NULL
  } else {
    error <- NULL
  }

  list(
    success = !is_error,
    elapsed = elapsed,
    output = output,
    model = model,
    ir = x,
    error = error)
}
